# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20160609_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_rating', models.IntegerField()),
                ('rating_count', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieratings.Movie')),
            ],
        ),
    ]
