# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 19:39
from __future__ import unicode_literals

from django.db import migrations


def import_avg_data(apps, schema_editor):
    from django.db.models import Avg
    Rating = apps.get_model("movieratings", "Rating")
    Movie = apps.get_model("movieratings", "Movie")
    Average = apps.get_model("movieratings", "Average")

    movie_list = Movie.objects.all()
    for movie_obj in movie_list:
        temp_avg = Rating.objects.filter(item_id=movie_obj.id).aggregate(Avg('rating'))
        average = list(temp_avg.values())[0]
        rating_count = Rating.objects.filter(item_id=movie_obj.id).count()
        Average.objects.create(
            movie_id=movie_obj,
            movie_rating=average,
            rating_count=rating_count
        )
    # raise Exception("1 yay")


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0006_average'),
    ]

    operations = [
        migrations.RunPython(import_avg_data)
    ]
