# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_average'),
    ]

    operations = [
        migrations.RunPython(import_avg_data)
    ]
